### ISSUE TITLE
Sort order in index pages

### ISSUE THREAD

**Issue by fam2342** [theobald-software/kb.theobald-software.github.io#7]
Is there any sort order at all? Is there a way to influence it? I would prefer alphabatic sorting.

Examples:
https://kb.theobald-software.com/erpconnect-general
https://kb.theobald-software.com/version-history

**Comment by Zuteilungsreif** [comment]
We changed it from alphabetical order to manual weight as requested by CT.



Sent from my Samsung Galaxy smartphone.


-------- Original message --------

**Comment by fam2342** [comment]
Is this a global setting or can it be changed on a per-index-site basis?

**Comment by Zuteilungsreif** [comment]
Currently its a global setting.
If we want anything else, should be no problem to correct it...
Just let me know



Sent from my Samsung Galaxy smartphone.


-------- Original message --------

**Comment by fam2342** [comment]
Well, manual ordering seems to make sense for most of the index pages. I wil manually sort the version history alphabetically then, shouldn't be too hard ;-)
